spring.application.name=queryapi
spring.datasource.url=jdbc:postgresql://dpg-d76bou3uibrs73bi6eq0-a.ohio-postgres.render.com:5432/ussd_mlqa
spring.datasource.username=root
spring.datasource.password=hi53OsvUYlf3VQtO1kGY08XD2Y8WcfCE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect